---

# System
podman_user: apprunner
podman_user_home: "/home/{{ podman_user }}"

# Domains
ntfy_domain: "ntfy.{{ base_domain_services }}"
kitchenowl_domain: "kitchenowl.{{ base_domain_services }}"
mollysocket_domain: "mollysocket.{{ base_domain_services }}"

landzunge_domain: "{{ base_domain_landzunge }}"
landzunge_api_domain: "api.{{ base_domain_landzunge }}"
landzunge_admin_domain: "admin.{{ base_domain_landzunge }}"

# Mollysocket
mollysocket_allowed_endpoints:
  - "https://{{ ntfy_domain }}"

# Landzunge
landzunge_cors_origins:
  - "https://{{ landzunge_domain }}"
  - "https://{{ landzunge_admin_domain }}"
